"""Phase 7 迁移模板：先把可安全准备的任务定义固化下来。"""


DAILY_SIGN_TOOL_PARAMS = {
    "r13_account_id": "r13_default",
    "problem_account_id": "ronghui_daxiang_s",
    "sign_account_id": "ronghui_daxiang_s",
    "detail_account_id": "ronghui_daxiang_s",
    "days": 7,
}

RONGHUI_DEFAULT_TOOL_PARAMS = {"account_id": "ronghui_default"}

PHASE7_SCHEDULED_TASK_TEMPLATES = [
    {
        "id": "send_order_2150",
        "name": "获取当日寄件数据",
        "tool_name": "sync_daily_send_orders",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "50 21 * * *",
        "enabled": False,
        "source": "phase7-first-batch",
    },
    {
        "id": "clockin_daxiang_1830",
        "name": "网点打卡-大祥",
        "tool_name": "clock_in_dual",
        "tool_params": {
            # Historical configuration did not persist the two authoritative
            # site codes.  This disabled template therefore fails validation
            # until an administrator supplies them; names are never guessed.
            "sitename": "邵阳大祥站",
            "sitefbname": "邵阳操作场",
            "first_type": "交件到港",
            "second_type": "接件离港",
            "delay_seconds": 2,
        },
        "cron_expression": "30 18 * * *",
        "enabled": False,
        "source": "phase7-first-batch",
    },
    {
        "id": "clockin_daxiang_s_1830",
        "name": "网点打卡-大祥S站",
        "tool_name": "clock_in_dual",
        "tool_params": {
            "sitecode": "7390017",
            "sitefbcode": "73901",
            "sitename": "邵阳大祥S站",
            "sitefbname": "邵阳操作场",
            "first_type": "交件到港",
            "second_type": "接件离港",
            "delay_seconds": 2,
        },
        "cron_expression": "33 18 * * *",
        "enabled": False,
        "source": "phase7-first-batch",
    },
    {
        "id": "r7_arrival_checkin",
        "name": "R7 到达打卡",
        "tool_name": "r7_arrival_checkin",
        "tool_params": {
            "headless": True,
            "slow_mo_ms": 0,
            "max_login_attempts": 6,
            "status_text": "车辆到达",
            "verify_status_text": "已到达",
            "flow_mode": 1,
            "do_arrive_wait_unload": True,
            "after_action_delay_ms": 1500,
            "daily_success_limit": 1,
        },
        "cron_expression": "0 19 * * *",
        "enabled": False,
        "source": "phase7-r7-checkin",
    },
    {
        "id": "r7_departure_checkin",
        "name": "R7 发车打卡",
        "tool_name": "r7_departure_checkin",
        "tool_params": {
            "headless": True,
            "slow_mo_ms": 0,
            "max_login_attempts": 6,
            "status_text": "已调度",
            "verify_status_text": "装车待发",
            "class_name": "邵阳操作场-长沙",
            "departure_time_fixed": "21:30:00",
            "plate_numbers": "湘AK6980",
            "do_departure_checkin": True,
            "after_action_delay_ms": 1500,
            "daily_success_limit": 1,
        },
        "cron_expression": "",
        "enabled": False,
        "source": "phase7-r7-checkin",
    },
    {
        "id": "daily_sign_0500",
        "name": "每日应签-05:00",
        "tool_name": "sync_daily_should_sign",
        "tool_params": dict(DAILY_SIGN_TOOL_PARAMS),
        "cron_expression": "0 5 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "daily_sign_0700",
        "name": "每日应签-07:00",
        "tool_name": "sync_daily_should_sign",
        "tool_params": dict(DAILY_SIGN_TOOL_PARAMS),
        "cron_expression": "0 7 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "daily_sign_0900",
        "name": "每日应签-09:00",
        "tool_name": "sync_daily_should_sign",
        "tool_params": dict(DAILY_SIGN_TOOL_PARAMS),
        "cron_expression": "0 9 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "daily_sign_1400",
        "name": "每日应签-14:00",
        "tool_name": "sync_daily_should_sign",
        "tool_params": dict(DAILY_SIGN_TOOL_PARAMS),
        "cron_expression": "0 14 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "daily_sign_1530",
        "name": "每日应签-15:30",
        "tool_name": "sync_daily_should_sign",
        "tool_params": dict(DAILY_SIGN_TOOL_PARAMS),
        "cron_expression": "30 15 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "daily_sign_1800",
        "name": "每日应签-18:00",
        "tool_name": "sync_daily_should_sign",
        "tool_params": dict(DAILY_SIGN_TOOL_PARAMS),
        "cron_expression": "0 18 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "customer_problems_shadow",
        "name": "客服问题件事项影子采集",
        "tool_name": "sync_customer_service_problems",
        "tool_params": {"direction": "both"},
        "cron_expression": "*/15 * * * *",
        "enabled": True,
        "source": "control-plane-pilot",
    },
    {
        "id": "site_send_0500",
        "name": "网点出港清单-05:00",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "0 5 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_0530",
        "name": "网点出港清单-05:30",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "30 5 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_1800",
        "name": "网点出港清单-18:00",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "0 18 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_1900",
        "name": "网点出港清单-19:00",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "0 19 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_1930",
        "name": "网点出港清单-19:30",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "30 19 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_2000",
        "name": "网点出港清单-20:00",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "0 20 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_2030",
        "name": "网点出港清单-20:30",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "30 20 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "site_send_2100",
        "name": "网点出港清单-21:00",
        "tool_name": "sync_site_send_list",
        "tool_params": dict(RONGHUI_DEFAULT_TOOL_PARAMS),
        "cron_expression": "0 21 * * *",
        "enabled": False,
        "source": "phase7-second-batch",
    },
    {
        "id": "finance_bills_0010",
        "name": "财务账单同步-00:10",
        "tool_name": "sync_finance_bills",
        "tool_params": {
            "mode": "sync",
            "platform": "ronghui",
            "rescan_days": 7,
        },
        "cron_expression": "10 0 * * *",
        "enabled": True,
        "source": "finance-ledger",
    },
    {
        "id": "yunda_dispatch_forecast_1700",
        "name": "韵达网点派件量预测-17:00",
        "tool_name": "sync_yunda_dispatch_forecast",
        "tool_params": {
            "account_id": "yunda_default",
            "dest_brch": "56739382",
        },
        "cron_expression": "0 17 * * *",
        "enabled": True,
        "source": "yunda-dispatch-forecast",
    },
]
