"""Schema requirements for the shared orchestration repositories."""

from __future__ import annotations


REQUIRED_TABLES = frozenset(
    {
        "admin_users",
        "arrival_forecast_runs",
        "arrival_forecast_items",
        "arrival_stat_runs",
        "arrival_stat_items",
        "agent_commands",
        "work_items",
        "work_item_entities",
        "agent_runs",
        "agent_run_steps",
        "approval_requests",
        "approval_decisions",
        "evidence_records",
        "external_entity_links",
        "domain_events",
        "outbox_events",
        "event_consumptions",
        "scheduled_task_approval_policies",
        "scheduled_task_approval_policy_events",
        "tool_logs",
        "waybill_problem_events",
        "waybill_sign_events",
        "daily_sign_ledger",
        "daily_sign_sync_runs",
    }
)

REQUIRED_COLUMNS = frozenset(
    {
        ("admin_users", "control_plane_role"),
        ("agent_commands", "command_id"),
        ("agent_commands", "idempotency_key"),
        ("agent_commands", "correlation_id"),
        ("agent_commands", "parameters_json"),
        ("work_items", "work_item_id"),
        ("work_items", "dedupe_key"),
        ("work_items", "owner_type"),
        ("work_items", "owner_id"),
        ("work_items", "version"),
        ("agent_runs", "run_id"),
        ("agent_runs", "plan_hash"),
        ("agent_runs", "tool_catalog_sha256"),
        ("agent_runs", "context_fingerprint_sha256"),
        ("agent_runs", "next_attempt_at"),
        ("agent_runs", "worker_id"),
        ("agent_runs", "lease_expires_at"),
        ("agent_runs", "cancel_requested_at"),
        ("agent_runs", "version"),
        ("agent_run_steps", "step_id"),
        ("agent_run_steps", "operation_type"),
        ("agent_run_steps", "risk_level"),
        ("agent_run_steps", "idempotency_key"),
        ("approval_requests", "approval_id"),
        ("approval_requests", "plan_hash"),
        ("approval_requests", "required_role"),
        ("approval_requests", "expires_at"),
        ("approval_decisions", "decision_id"),
        ("evidence_records", "evidence_id"),
        ("evidence_records", "content_sha256"),
        ("external_entity_links", "link_id"),
        ("domain_events", "event_id"),
        ("domain_events", "payload_sha256"),
        ("outbox_events", "outbox_id"),
        ("outbox_events", "locked_until"),
        ("outbox_events", "attempt_count"),
        ("event_consumptions", "consumer_name"),
        ("event_consumptions", "event_id"),
        ("scheduled_tasks", "configuration_version"),
        ("scheduled_tasks", "updated_at"),
        ("scheduled_task_approval_policies", "task_id"),
        ("scheduled_task_approval_policies", "mode"),
        ("scheduled_task_approval_policies", "contract_hash"),
        ("scheduled_task_approval_policies", "version"),
        ("scheduled_task_approval_policy_events", "event_id"),
        ("scheduled_task_approval_policy_events", "request_id"),
        ("scheduled_task_approval_policy_events", "task_id"),
        ("tool_logs", "run_id"),
        ("tool_logs", "step_id"),
        ("tool_logs", "correlation_id"),
    }
)
